app:
  name: go-gateway
  env: dev
  middleware_path: ./config/middleware
  upstream:
    config_path: ./config/upstreams
    items:
      - order_service

server:
  host: 0.0.0.0
  port: 8080
  read_timeout_ms: 5000
  write_timeout_ms: 5000